apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - openwebui-deployment.yaml
  - openwebui-ingress.yaml
  - openwebui-pvc.yaml
  - openwebui-service.yaml
  - openwebui-pv.yaml
  - openwebui-storage-class.yaml
