apiVersion: v1
kind: PersistentVolume
metadata:
  name: openwebui-pv
spec:
  storageClassName: manual
  capacity:
    storage: 64Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /opt/sotongpt/openwebui-data
    type: DirectoryOrCreate
