apiVersion: v1
kind: PersistentVolume
metadata:
  name: openwebui-pv
spec:
  storageClassName: manual
  claimRef:
    name: openwebui-pvc
    namespace: sotongpt
  capacity:
    storage: 32Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /opt/sotongpt/openwebui-data
    type: DirectoryOrCreate
