apiVersion: v1
kind: Service
metadata:
  name: vllm-gpt-oss-20b
  namespace: sotongpt
spec:
  ports:
  - name: vllm-gpt-oss-20b
    port: 80
    protocol: TCP
    targetPort: 8000
  # The label selector should match the deployment labels & it is useful for prefix caching feature
  selector:
    app: vllm-gpt-oss-20b-deployment
  sessionAffinity: None
  type: ClusterIP
