apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/
  - ../../services/ollama
  - ../../services/web-chat
nameSuffix: -ollama-dev
labels:
  - includeSelectors: true
    pairs:
      env: dev
