apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - vllm-deepseek-r1-qwen-32b-deployment.yaml
  - vllm-deepseek-r1-qwen-32b-pv.yaml
  - vllm-deepseek-r1-qwen-32b-pvc.yaml
  - vllm-deepseek-r1-qwen-32b-service.yaml
