apiVersion: v1
kind: Service
metadata:
  name: vllm-server
  namespace: sotongpt
spec:
  ports:
  - name: http-vllm-server
    port: 80
    protocol: TCP
    targetPort: 8000
  # The label selector should match the deployment labels & it is useful for prefix caching feature
  selector:
    app: vllm-server
  sessionAffinity: None
  type: ClusterIP
