apiVersion: v1
kind: Service
metadata:
  name: vllm-llama-3b
  namespace: sotongpt
spec:
  ports:
  - name: http-vllm-llama-3b
    port: 80
    protocol: TCP
    targetPort: 8000
  # The label selector should match the deployment labels & it is useful for prefix caching feature
  selector:
    app: vllm-llama-3b
  sessionAffinity: None
  type: ClusterIP