apiVersion: v1
kind: PersistentVolume
metadata:
  name: tiny-llama-pv
spec:
  storageClassName: manual
  claimRef:
    name: tiny-llama
    namespace: sotongpt
  capacity:
    storage: 64Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/ejp1v21/opt/sotongpt/vllm/tiny-llama
    type: DirectoryOrCreate
