apiVersion: v1
kind: Service
metadata:
  name: tiny-llama-service
  namespace: sotongpt
spec:
  ports:
    - name: tiny-llama
      port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    app: tiny-llama-deployment
  sessionAffinity: None
  type: ClusterIP
