apiVersion: v1
kind: Service
metadata:
  name: vllm-tiny-llama
  namespace: sotongpt
  labels:
    app: vllm
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    app: tiny-llama-deployment
  sessionAffinity: None
  type: ClusterIP
