apiVersion: v1
kind: PersistentVolume
metadata:
  name: qwen3-32b-pv
spec:
  storageClassName: manual
  claimRef:
    name: qwen3-32b-pvc
    namespace: sotongpt
  capacity:
    storage: 64Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/ejp1v21/opt/sotongpt/vllm/qwen3-32b
    type: DirectoryOrCreate
