apiVersion: v1
kind: Service
metadata:
  name: vllm-qwen3-32b
  namespace: sotongpt
  labels:
    app: vllm
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8000
  # The label selector should match the deployment labels & it is useful for prefix caching feature
  selector:
    app: vllm-qwen3-32b-deployment
  sessionAffinity: None
  type: ClusterIP
