apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ollama-service.yaml
  - ollama-deployment.yaml
  - openwebui-deployment.yaml
  - openwebui-service.yaml
  - openwebui-ingress.yaml
  - openwebui-pvc.yaml
