apiVersion: v1
kind: Service
metadata:
  name: vllm-deepseek-r1-qwen-32b
  namespace: sotongpt
spec:
  ports:
    - name: vllm-deepseek-r1-qwen-32b
      port: 80
      protocol: TCP
      targetPort: 8000
  # The label selector should match the deployment labels & it is useful for prefix caching feature
  selector:
    app: vllm-deepseek-r1-qwen-32b-deployment
  sessionAffinity: None
  type: ClusterIP
