apiVersion: v1
kind: PersistentVolume
metadata:
  name: llama3-70b-pv
spec:
  storageClassName: manual
  claimRef:
    name: llama3-70b-pvc
    namespace: sotongpt
  capacity:
    storage: 64Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/ejp1v21/opt/sotongpt/vllm/llama3-70b
    type: DirectoryOrCreate
