apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgres-configmap.yaml
  - postgres-deployment.yaml
  - postgres-pv.yaml
  - postgres-pvc.yaml
  - postgres-secret.yaml
  - postgres-service.yaml
