apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
spec:
  storageClassName: manual
  claimRef:
    name: postgres-pvc
    namespace: sotongpt
  capacity:
    storage: 64Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /opt/sotongpt/postgresql
    type: DirectoryOrCreate
