apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-background-tasks-deployment
  namespace: sotongpt
  labels:
    app: ollama-background-tasks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama-background-tasks
  template:
    metadata:
      labels:
        app: ollama-background-tasks
    spec:
      containers:
        - name: ollama
          image: ollama/ollama:0.15.4
          ports:
            - containerPort: 11434
          resources:
            requests:
              cpu: 4
              memory: 4Gi
            limits:
              cpu: 6
              memory: 8Gi
          volumeMounts:
            - name: ollama-background-tasks-storage
              mountPath: /root/.ollama
      volumes:
        - name: ollama-background-tasks-storage
          persistentVolumeClaim:
            claimName: ollama-background-tasks-pvc
