apiVersion: v1
kind: Service
metadata:
  name: ollama-background-tasks
  namespace: sotongpt
  labels:
    app: ollama
spec:
  selector:
    app: ollama-background-tasks
  ports:
    - protocol: TCP
      port: 11434
      targetPort: 11434
