apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-qwen2-5-32b-instruct-deployment
  namespace: sotongpt
  labels:
    app: vllm-qwen2-5-32b-instruct-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vllm-qwen2-5-32b-instruct-deployment
  template:
    metadata:
      labels:
        app: vllm-qwen2-5-32b-instruct-deployment
    spec:
      volumes:
        - name: cache-volume
          persistentVolumeClaim:
            claimName: qwen2-5-32b-instruct-pvc
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: 16Gi
      containers:
        - name: vllm
          image: vllm/vllm-openai:v0.14.1
          args:
            - Qwen/Qwen2.5-32B-Instruct-AWQ
            - --tensor-parallel-size
            - "2"
            - --dtype
            - float16
            - --quantization
            - awq
            - --max-model-len
            - "100000"
            - --gpu-memory-utilization
            - "0.85"
            - --enable-chunked-prefill
            - --max-num-batched-tokens
            - "2048"
            - --host
            - 0.0.0.0
            - --port
            - "8000"
          ports:
            - containerPort: 8000
          env:
            - name: VLLM_LOGGING_LEVEL
              value: INFO
            - name: VLLM_ALLOW_LONG_MAX_MODEL_LEN
              value: "1"
          resources:
            limits:
              nvidia.com/gpu: "2"
              cpu: "8"
              memory: 96Gi
            requests:
              nvidia.com/gpu: "2"
              cpu: "4"
              memory: 32Gi
          volumeMounts:
            - name: cache-volume
              mountPath: /root/.cache/huggingface
            - name: shm
              mountPath: /dev/shm
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            periodSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            periodSeconds: 5
            failureThreshold: 3
          # let's the container have 15 minutes to launch before k8s tries to
          # say that it's broken/not launching
          startupProbe:
            httpGet:
              path: /health
              port: 8000
            periodSeconds: 5
            failureThreshold: 180
