apiVersion: v1
kind: PersistentVolume
metadata:
  name: qwen2-5-32b-instruct-pv
spec:
  storageClassName: manual
  claimRef:
    name: qwen2-5-32b-instruct-pvc
    namespace: sotongpt
  capacity:
    storage: 64Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/ejp1v21/opt/sotongpt/vllm/qwen2-5-32b-instruct
    type: DirectoryOrCreate
