apiVersion: v1
kind: PersistentVolume
metadata:
  name: vllm-qwen3-14b-pv
spec:
  storageClassName: manual
  claimRef:
    name: qwen3-14b
    namespace: sotongpt
  capacity:
    storage: 64Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/ejp1v21/opt/sotongpt/vllm/qwen3-14b
    type: DirectoryOrCreate
