apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- base/
- services/ollama-background-tasks
- sercvices/vllm-deepseek-r1-qwen-32b
- services/vllm-qwen3-14b
- services/web-chat
- services/web-chat-database
labels:
- includeSelectors: true
  pairs:
    project: SotonGPT
