apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- base/
- services/ollama-background-tasks
- services/vllm-gemma3-27b
- services/vllm-qwen3
- services/web-chat
labels:
- includeSelectors: true
  pairs:
    project: SotonGPT
