apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- base/
- services/ollama-background-tasks
- services/vllm-qwen3-14b
- services/vllm-mistral-8x7b-instruct
- services/vllm-qwen3-0.6b
- services/web-chat
labels:
- includeSelectors: true
  pairs:
    project: SotonGPT
