apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- base/
- services/web-chat
- services/web-chat-database
- services/ollama-background-tasks
- services/vllm/secrets/secret.yaml
labels:
- includeSelectors: true
  pairs:
    project: SotonGPT
