apiVersion: v1
kind: Service
metadata:
  name: vllm-qwen2-5-14b-instruct
  namespace: sotongpt
spec:
  ports:
    - name: vllm-qwen2-5-14b-instruct
      port: 80
      protocol: TCP
      targetPort: 8000
  # The label selector should match the deployment labels & it is useful for prefix caching feature
  selector:
    app: vllm-qwen2_5-14b-instruct-deployment
  sessionAffinity: None
  type: ClusterIP
